### ISSUE TITLE
Como administrador quiero iniciar sesión para acceder al sistema.

### ISSUE THREAD

**Issue by DiegoLeon02** [DiegoLeon02/AquaSys#10]

**Comment by MilagroMR** [comment]
1. Escenario: 
El administrador debe ser redirigido a la página del menú principal. 

2. Escenario: 
El sistema debe mostrar un mensaje de error indicando que las credenciales son incorrectas. 

3. Escenario: 
El sistema debe de mostrar un mensaje de error informando que el usuario ya está registrado.

Contexto: 
1. En caso que el administrador se loguee exitosamente
2. En caso que el administrador se loguee con credenciales incorrectas. 
3. En caso que el usuario esté registrado en el sistema. 

Evento: 
1. Cuando el administrador inicia sesión.
2. Cuando el administrador inicia sesión.
3. Cuando el administrador inicia sesión.

Resultado: 
1.   El sistema permite el acceso al administrador, redirigiendolo a la pagina del menú principal. 
2. El sistema genera un mensaje de error a la hora de iniciar seción. 
3. El sistema genera un mensaje de error informando que ya existe el usuario.
