### ISSUE TITLE
Como administrador  se gestiona mi cuenta la cual me permite tener varios opciones como crear, borrar y eliminar.

### ISSUE THREAD

**Issue by DiegoLeon02** [DiegoLeon02/AquaSys#11]

**Comment by MilagroMR** [comment]
1. Escenario: 
El administrador debe poder acceder a la opción de "cuenta" desde la página principal del sistema. 

2. Contexto: 
En caso que el administrador ingrese al apartado de "cuentas".

3. Evento: 
Cuando el administrador ingresa a "cuentas".

4. Resultado: 
El sistema redirige al apartado de "cuentas", donde podrá ver un botón de "opciones" donde podrá crear, borrar y actualizar la cuenta.
