### ISSUE TITLE
Como administrador quiero gestionar los roles de usuario para controlar el acceso a diferentes funciones, en la cual pueda crear, borrar y eliminar dichos roles.

### ISSUE THREAD

**Issue by DiegoLeon02** [DiegoLeon02/AquaSys#12]

**Comment by MilagroMR** [comment]
1. Escenario:  
El sistema debe mostrar una lista de todos los roles existentes y sus permisos asociados.

2. Contexto:
En caso que se necesite gestionar los permisos de los usuarios.

3. Evento: 
Cuando el administrador gestiona los roles

4. Resultado: 
El sistema permite crear, borrar y eliminar los roles y permisos de los usuarios mostrándolos en una lista, tanto el rol administrador, gerente, usuario y empleado por separado.
