### ISSUE TITLE
Como gestor de inventario quiero añadir/crear nuevos productos para mantener el stock actualizado.

### ISSUE THREAD

**Issue by DiegoLeon02** [DiegoLeon02/AquaSys#15]
Escenario

- Cuando el gestor de inventario añade un nuevo producto al sistema, este actualiza automáticamente el stock y registra la entrada del nuevo producto.
- Si el gestor de inventario introduce información incorrecta o incompleta sobre el producto, el sistema muestra un error indicando qué información falta o es incorrecta.
- Al intentar añadir un producto que ya existe con el mismo código de barras, el sistema alerta al gestor sobre la duplicidad y sugiere actualizar el stock existente en lugar de crear un nuevo registro.

Contexto

- En caso de que el gestor de inventario necesite añadir nuevos productos para mantener el stock actualizado y responder a las demandas del mercado.
- En caso de que el gestor de inventario ingrese datos incorrectos o incompletos durante el proceso de añadir un nuevo producto.
- En caso de que el gestor de inventario intente registrar un producto que ya existe en el sistema con exactamente los mismos detalles identificativos.

Evento

- Cuando el gestor de inventario accede al sistema y selecciona la opción 'Añadir nuevo producto' en el módulo de gestión de inventario.
- Cuando el gestor de inventario completa y envía el formulario de registro de nuevo producto.
- Cuando el sistema detecta que el código de barras del nuevo producto ya está registrado en el sistema.

Resultado

- El sistema añade el nuevo producto al inventario, actualiza la cantidad disponible y proporciona una confirmación visual de que el producto ha sido añadido correctamente.
- El sistema muestra un mensaje de error específico que indica los campos que necesitan ser corregidos o completados antes de que el registro del producto pueda ser exitoso.
- El sistema avisa al gestor sobre la duplicidad y ofrece opciones para actualizar el stock existente o revisar la información del producto existente para evitar conflictos en el inventario.

**Comment by MilagroMR** [comment]
**1. Escenarios:** 
1. Producto existente. 
2. Error en campos incompletos
3. Agregación de producto exitosa

**2. Contextos:** 
1. En caso que agregue o cree un producto que ya existe. 
2. En caso que agregue un producto y no estoy llenando todos los campos obligatorios.
3. En caso que agregue un producto de forma correcta. 

**3. Eventos:** 
1. Cuando el gestor añade el producto.
2. Cuando el gestor intente agregar un nuevo producto.
3. Cuando el gestor agregue un producto.

**4. Resultados:** 
1. El sistema genera un mensaje de error informando que el producto ya existe. 
2. El sistema genera un mensaje de error informando "Complete todos los espacios solicitados". 
3. El sistema genera un mensaje de exito "Producto añadido correctamente".
